name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    defaults:
      run:
        working-directory: sim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3

      - name: Configure Poetry
        run: poetry config virtualenvs.create true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Ruff
        run: poetry run ruff check src tests

      - name: Black
        run: poetry run black --check src tests

      - name: isort
        run: poetry run isort --check-only src tests

      - name: mypy
        run: poetry run mypy src

      - name: pytest
        run: poetry run pytest --cov=ki_dev_tycoon --cov-report=term-missing --cov-fail-under=90

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: sim/.coverage*
          if-no-files-found: ignore
